[book]
authors = ["unclepomedev"]
language = "zh"
src = "src"
title = "SavePoints 用户手册"

[output.html]
git-repository-url = "https://github.com/unclepomedev/blender_savepoints"
site-url = "/blender_savepoints/zh/"
theme = "../theme"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
