# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.DepsgraphObjectInstance.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct
from .Object import Object
from .ParticleSystem import ParticleSystem

class DepsgraphObjectInstance(bpy_struct):

    @property
    def object(self) -> Annotated[Optional['Object'], "is_animatable=False"]:
        """Evaluated object the iterator points to"""
        ...
    @property
    def show_self(self) -> Annotated[bool, "is_animatable=False"]:
        """The object geometry itself should be visible in the render"""
        ...
    @property
    def show_particles(self) -> Annotated[bool, "is_animatable=False"]:
        """Particles part of the object should be visible in the render"""
        ...
    @property
    def is_instance(self) -> Annotated[bool, "is_animatable=False"]:
        """Denotes if the object is generated by another object"""
        ...
    @property
    def instance_object(self) -> Annotated[Optional['Object'], "is_animatable=False"]:
        """Evaluated object which is being instanced by this iterator"""
        ...
    @property
    def parent(self) -> Annotated[Optional['Object'], "is_animatable=False"]:
        """If the object is an instance, the parent object that generated it"""
        ...
    @property
    def particle_system(self) -> Annotated[Optional['ParticleSystem'], "is_animatable=False"]:
        """Evaluated particle system that this object was instanced from"""
        ...
    @property
    def persistent_id(self) -> Annotated[list[int], "step=1", "is_animatable=False"]:
        """Persistent identifier for inter-frame matching of objects with motion blur"""
        ...
    @property
    def random_id(self) -> Annotated[int, "subtype='UNSIGNED'", "step=1", "is_animatable=False"]:
        """Random id for this instance, typically for randomized shading"""
        ...
    @property
    def matrix_world(self) -> Annotated[list[float], "subtype='MATRIX'", "step=10.0", "precision=3", "is_animatable=False"]:
        """Generated transform matrix in world space"""
        ...
    @property
    def orco(self) -> Annotated[list[float], "subtype='TRANSLATION'", "unit='LENGTH'", "step=10.0", "precision=3", "is_animatable=False"]:
        """Generated coordinates in parent object space"""
        ...
    @property
    def uv(self) -> Annotated[list[float], "step=10.0", "precision=3", "is_animatable=False"]:
        """UV coordinates in parent object space"""
        ...