# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.FModifierFunctionGenerator.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .FModifier import FModifier

class FModifierFunctionGenerator(FModifier):

    @property
    def name(self) -> Annotated[str, "is_animatable=False"]:
        """F-Curve Modifier name"""
        ...
    @name.setter
    def name(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def type(self) -> Literal['NULL', 'GENERATOR', 'FNGENERATOR', 'ENVELOPE', 'CYCLES', 'NOISE', 'LIMITS', 'STEPPED']:
        """F-Curve Modifier Type"""
        ...
    @property
    def show_expanded(self) -> bool:
        """F-Curve Modifier's panel is expanded in UI"""
        ...
    @show_expanded.setter
    def show_expanded(self, value: bool):
        ...
    @property
    def mute(self) -> bool:
        """Enable F-Curve modifier evaluation"""
        ...
    @mute.setter
    def mute(self, value: bool):
        ...
    @property
    def is_valid(self) -> bool:
        """F-Curve Modifier has invalid settings and will not be evaluated"""
        ...
    @property
    def active(self) -> bool:
        """F-Curve modifier will show settings in the editor"""
        ...
    @active.setter
    def active(self, value: bool):
        ...
    @property
    def use_restricted_range(self) -> bool:
        """F-Curve Modifier is only applied for the specified frame range to help mask off effects in order to chain them"""
        ...
    @use_restricted_range.setter
    def use_restricted_range(self, value: bool):
        ...
    @property
    def frame_start(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Frame that modifier's influence starts (if Restrict Frame Range is in use)"""
        ...
    @frame_start.setter
    def frame_start(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def frame_end(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Frame that modifier's influence ends (if Restrict Frame Range is in use)"""
        ...
    @frame_end.setter
    def frame_end(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def blend_in(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Number of frames from start frame for influence to take effect"""
        ...
    @blend_in.setter
    def blend_in(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def blend_out(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Number of frames from end frame for influence to fade out"""
        ...
    @blend_out.setter
    def blend_out(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def use_influence(self) -> bool:
        """F-Curve Modifier's effects will be tempered by a default factor"""
        ...
    @use_influence.setter
    def use_influence(self, value: bool):
        ...
    @property
    def influence(self) -> Annotated[float, "subtype='FACTOR'", "step=10.0", "precision=3"]:
        """Amount of influence F-Curve Modifier will have when not fading in/out"""
        ...
    @influence.setter
    def influence(self, value: Annotated[float, "subtype='FACTOR'", "step=10.0", "precision=3"]):
        ...
    @property
    def amplitude(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Scale factor determining the maximum/minimum values"""
        ...
    @amplitude.setter
    def amplitude(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def phase_multiplier(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Scale factor determining the 'speed' of the function"""
        ...
    @phase_multiplier.setter
    def phase_multiplier(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def phase_offset(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Constant factor to offset time by for function"""
        ...
    @phase_offset.setter
    def phase_offset(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def value_offset(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """Constant factor to offset values by"""
        ...
    @value_offset.setter
    def value_offset(self, value: Annotated[float, "step=10.0", "precision=3"]):
        ...
    @property
    def use_additive(self) -> bool:
        """Values generated by this modifier are applied on top of the existing values instead of overwriting them"""
        ...
    @use_additive.setter
    def use_additive(self, value: bool):
        ...
    @property
    def function_type(self) -> Literal['SIN', 'COS', 'TAN', 'SQRT', 'LN', 'SINC']:
        """Type of built-in function to use"""
        ...
    @function_type.setter
    def function_type(self, value: Literal['SIN', 'COS', 'TAN', 'SQRT', 'LN', 'SINC']):
        ...