# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated
from .bpy_prop_collection import bpy_prop_collection

from .FModifier import FModifier
class FModifierFunctionGenerator(FModifier):
    name: Annotated[str, "is_animatable=False"]
    """F-Curve Modifier name"""
    @property
    def type(self) -> Literal['NULL', 'GENERATOR', 'FNGENERATOR', 'ENVELOPE', 'CYCLES', 'NOISE', 'LIMITS', 'STEPPED']:
        """F-Curve Modifier Type"""
        ...
    show_expanded: bool
    """F-Curve Modifier's panel is expanded in UI"""
    mute: bool
    """Enable F-Curve modifier evaluation"""
    @property
    def is_valid(self) -> bool:
        """F-Curve Modifier has invalid settings and will not be evaluated"""
        ...
    active: bool
    """F-Curve modifier will show settings in the editor"""
    use_restricted_range: bool
    """F-Curve Modifier is only applied for the specified frame range to help mask off effects in order to chain them"""
    frame_start: Annotated[float, "step=10.0", "precision=3"]
    """Frame that modifier's influence starts (if Restrict Frame Range is in use)"""
    frame_end: Annotated[float, "step=10.0", "precision=3"]
    """Frame that modifier's influence ends (if Restrict Frame Range is in use)"""
    blend_in: Annotated[float, "step=10.0", "precision=3"]
    """Number of frames from start frame for influence to take effect"""
    blend_out: Annotated[float, "step=10.0", "precision=3"]
    """Number of frames from end frame for influence to fade out"""
    use_influence: bool
    """F-Curve Modifier's effects will be tempered by a default factor"""
    influence: Annotated[float, "subtype='FACTOR'", "step=10.0", "precision=3"]
    """Amount of influence F-Curve Modifier will have when not fading in/out"""
    amplitude: Annotated[float, "step=10.0", "precision=3"]
    """Scale factor determining the maximum/minimum values"""
    phase_multiplier: Annotated[float, "step=10.0", "precision=3"]
    """Scale factor determining the 'speed' of the function"""
    phase_offset: Annotated[float, "step=10.0", "precision=3"]
    """Constant factor to offset time by for function"""
    value_offset: Annotated[float, "step=10.0", "precision=3"]
    """Constant factor to offset values by"""
    use_additive: bool
    """Values generated by this modifier are applied on top of the existing values instead of overwriting them"""
    function_type: Literal['SIN', 'COS', 'TAN', 'SQRT', 'LN', 'SINC']
    """Type of built-in function to use"""