# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.GeometryNodeGridDivergence.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .GeometryNode import GeometryNode
from .Node import Node
from .NodeInputs import NodeInputs
from .NodeLink import NodeLink
from .NodeOutputs import NodeOutputs
from .NodeSocket import NodeSocket
from .bpy_prop_collection import bpy_prop_collection

class GeometryNodeGridDivergence(GeometryNode):

    @property
    def type(self) -> Annotated[str, "is_animatable=False"]:
        """Legacy unique node type identifier, redundant with bl_idname property"""
        ...
    @property
    def location(self) -> Annotated[list[float], "subtype='XYZ'", "step=10.0", "precision=3"]:
        """Location of the node within its parent frame"""
        ...
    @location.setter
    def location(self, value: Annotated[list[float], "subtype='XYZ'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def location_absolute(self) -> Annotated[list[float], "subtype='XYZ'", "step=10.0", "precision=3"]:
        """Location of the node in the entire canvas"""
        ...
    @location_absolute.setter
    def location_absolute(self, value: Annotated[list[float], "subtype='XYZ'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def width(self) -> Annotated[float, "subtype='XYZ'", "step=10.0", "precision=3"]:
        """Width of the node"""
        ...
    @width.setter
    def width(self, value: Annotated[float, "subtype='XYZ'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def height(self) -> Annotated[float, "subtype='XYZ'", "step=10.0", "precision=3"]:
        """Height of the node"""
        ...
    @height.setter
    def height(self, value: Annotated[float, "subtype='XYZ'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def dimensions(self) -> Annotated[list[float], "subtype='XYZ_LENGTH'", "unit='LENGTH'", "step=10.0", "precision=3"]:
        """Absolute bounding box dimensions of the node"""
        ...
    @property
    def name(self) -> Annotated[str, "is_animatable=False"]:
        """Unique node identifier"""
        ...
    @name.setter
    def name(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def label(self) -> Annotated[str, "is_animatable=False"]:
        """Optional custom node label"""
        ...
    @label.setter
    def label(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def inputs(self) -> Annotated['NodeInputs', "is_animatable=False"]:

        ...
    @property
    def outputs(self) -> Annotated['NodeOutputs', "is_animatable=False"]:

        ...
    @property
    def internal_links(self) -> Annotated[bpy_prop_collection['NodeLink'], "is_animatable=False"]:
        """Internal input-to-output connections for muting"""
        ...
    @property
    def parent(self) -> Annotated[Optional['Node'], "is_animatable=False"]:
        """Parent this node is attached to"""
        ...
    @parent.setter
    def parent(self, value: Annotated[Optional['Node'], "is_animatable=False"]) -> None:
        ...
    @property
    def warning_propagation(self) -> Literal['ALL', 'NONE', 'ERRORS', 'ERRORS_AND_WARNINGS']:
        """The kinds of messages that should be propagated from this node to the parent group node"""
        ...
    @warning_propagation.setter
    def warning_propagation(self, value: Literal['ALL', 'NONE', 'ERRORS', 'ERRORS_AND_WARNINGS']) -> None:
        ...
    @property
    def use_custom_color(self) -> Annotated[bool, "is_animatable=False"]:
        """Use custom color for the node"""
        ...
    @use_custom_color.setter
    def use_custom_color(self, value: Annotated[bool, "is_animatable=False"]) -> None:
        ...
    @property
    def color(self) -> Annotated[list[float], "subtype='COLOR_GAMMA'", "step=10.0", "precision=3"]:
        """Custom color of the node body"""
        ...
    @color.setter
    def color(self, value: Annotated[list[float], "subtype='COLOR_GAMMA'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def color_tag(self) -> Literal['NONE', 'ATTRIBUTE', 'COLOR', 'CONVERTER', 'DISTORT', 'FILTER', 'GEOMETRY', 'INPUT', 'MATTE', 'OUTPUT', 'SCRIPT', 'SHADER', 'TEXTURE', 'VECTOR', 'PATTERN', 'INTERFACE', 'GROUP']:
        """Node header color tag"""
        ...
    @property
    def select(self) -> bool:
        """Node selection state"""
        ...
    @select.setter
    def select(self, value: bool) -> None:
        ...
    @property
    def show_options(self) -> bool:

        ...
    @show_options.setter
    def show_options(self, value: bool) -> None:
        ...
    @property
    def show_preview(self) -> bool:

        ...
    @show_preview.setter
    def show_preview(self, value: bool) -> None:
        ...
    @property
    def hide(self) -> bool:

        ...
    @hide.setter
    def hide(self, value: bool) -> None:
        ...
    @property
    def mute(self) -> Annotated[bool, "is_animatable=False"]:

        ...
    @mute.setter
    def mute(self, value: Annotated[bool, "is_animatable=False"]) -> None:
        ...
    @property
    def show_texture(self) -> bool:
        """Display node in viewport textured shading mode"""
        ...
    @show_texture.setter
    def show_texture(self, value: bool) -> None:
        ...
    @property
    def bl_idname(self) -> Annotated[str, "is_animatable=False"]:

        ...
    @bl_idname.setter
    def bl_idname(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def bl_label(self) -> Annotated[str, "is_animatable=False"]:
        """The node label"""
        ...
    @bl_label.setter
    def bl_label(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def bl_description(self) -> Annotated[str, "subtype='TRANSLATION'", "unit='LENGTH'", "is_animatable=False"]:

        ...
    @bl_description.setter
    def bl_description(self, value: Annotated[str, "subtype='TRANSLATION'", "unit='LENGTH'", "is_animatable=False"]) -> None:
        ...
    @property
    def bl_icon(self) -> str:
        """The node icon"""
        ...
    @bl_icon.setter
    def bl_icon(self, value: str) -> None:
        ...
    @property
    def bl_static_type(self) -> Annotated[str, "is_animatable=False"]:
        """Legacy unique node type identifier, redundant with bl_idname property"""
        ...
    @property
    def bl_width_default(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_width_default.setter
    def bl_width_default(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def bl_width_min(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_width_min.setter
    def bl_width_min(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def bl_width_max(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_width_max.setter
    def bl_width_max(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def bl_height_default(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_height_default.setter
    def bl_height_default(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def bl_height_min(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_height_min.setter
    def bl_height_min(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    @property
    def bl_height_max(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:

        ...
    @bl_height_max.setter
    def bl_height_max(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]) -> None:
        ...
    def bl_system_properties_get(self, *args, **kwargs) -> Any: ...
    def socket_value_update(self, *args, **kwargs) -> Any: ...
    def is_registered_node_type(self, *args, **kwargs) -> Any: ...
    def poll(self, *args, **kwargs) -> Any: ...
    def poll_instance(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def insert_link(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def free(self, *args, **kwargs) -> Any: ...
    def draw_buttons(self, *args, **kwargs) -> Any: ...
    def draw_buttons_ext(self, *args, **kwargs) -> Any: ...
    def draw_label(self, *args, **kwargs) -> Any: ...
    def debug_zone_body_lazy_function_graph(self, *args, **kwargs) -> Any: ...
    def debug_zone_lazy_function_graph(self, *args, **kwargs) -> Any: ...
    def poll(self, *args, **kwargs) -> Any: ...
    def poll_instance(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def draw_buttons(self, *args, **kwargs) -> Any: ...
    def draw_buttons_ext(self, *args, **kwargs) -> Any: ...
    def is_registered_node_type(self, *args, **kwargs) -> Any: ...
    def input_template(self, *args, **kwargs) -> Any: ...
    def output_template(self, *args, **kwargs) -> Any: ...