# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.GreasePencilv3LayerGroup.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct
from .GreasePencilLayerGroup import GreasePencilLayerGroup

class GreasePencilv3LayerGroup(bpy_struct):

    active: Annotated[Optional['GreasePencilLayerGroup'], "is_animatable=False"]
    """Active Grease Pencil layer group"""
    def new(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def move(self, *args, **kwargs) -> Any: ...
    def move_top(self, *args, **kwargs) -> Any: ...
    def move_bottom(self, *args, **kwargs) -> Any: ...
    def move_to_layer_group(self, *args, **kwargs) -> Any: ...
    def __contains__(self, key: Union[str, int]) -> bool: ...
    def __iter__(self) -> Iterator['GreasePencilLayerGroup']: ...
    def __getitem__(self, key: Union[str, int]) -> 'GreasePencilLayerGroup': ...
    def __len__(self) -> int: ...