# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated
from .bpy_prop_collection import bpy_prop_collection

from .Modifier import Modifier
from .Collection import Collection
from .Material import Material
from .Object import Object
class GreasePencilLineartModifier(Modifier):
    name: Annotated[str, "is_animatable=False"]
    """Modifier name"""
    @property
    def type(self) -> Literal['GREASE_PENCIL_VERTEX_WEIGHT_PROXIMITY', 'DATA_TRANSFER', 'MESH_CACHE', 'MESH_SEQUENCE_CACHE', 'NORMAL_EDIT', 'WEIGHTED_NORMAL', 'UV_PROJECT', 'UV_WARP', 'VERTEX_WEIGHT_EDIT', 'VERTEX_WEIGHT_MIX', 'VERTEX_WEIGHT_PROXIMITY', 'GREASE_PENCIL_COLOR', 'GREASE_PENCIL_TINT', 'GREASE_PENCIL_OPACITY', 'GREASE_PENCIL_VERTEX_WEIGHT_ANGLE', 'GREASE_PENCIL_TIME', 'GREASE_PENCIL_TEXTURE', 'ARRAY', 'BEVEL', 'BOOLEAN', 'BUILD', 'DECIMATE', 'EDGE_SPLIT', 'NODES', 'MASK', 'MIRROR', 'MESH_TO_VOLUME', 'MULTIRES', 'REMESH', 'SCREW', 'SKIN', 'SOLIDIFY', 'SUBSURF', 'TRIANGULATE', 'VOLUME_TO_MESH', 'WELD', 'WIREFRAME', 'GREASE_PENCIL_ARRAY', 'GREASE_PENCIL_BUILD', 'GREASE_PENCIL_LENGTH', 'LINEART', 'GREASE_PENCIL_MIRROR', 'GREASE_PENCIL_MULTIPLY', 'GREASE_PENCIL_SIMPLIFY', 'GREASE_PENCIL_SUBDIV', 'GREASE_PENCIL_ENVELOPE', 'GREASE_PENCIL_OUTLINE', 'ARMATURE', 'CAST', 'CURVE', 'DISPLACE', 'HOOK', 'LAPLACIANDEFORM', 'LATTICE', 'MESH_DEFORM', 'SHRINKWRAP', 'SIMPLE_DEFORM', 'SMOOTH', 'CORRECTIVE_SMOOTH', 'LAPLACIANSMOOTH', 'SURFACE_DEFORM', 'WARP', 'WAVE', 'VOLUME_DISPLACE', 'GREASE_PENCIL_HOOK', 'GREASE_PENCIL_NOISE', 'GREASE_PENCIL_OFFSET', 'GREASE_PENCIL_SMOOTH', 'GREASE_PENCIL_THICKNESS', 'GREASE_PENCIL_LATTICE', 'GREASE_PENCIL_DASH', 'GREASE_PENCIL_ARMATURE', 'GREASE_PENCIL_SHRINKWRAP', 'CLOTH', 'COLLISION', 'DYNAMIC_PAINT', 'EXPLODE', 'FLUID', 'OCEAN', 'PARTICLE_INSTANCE', 'PARTICLE_SYSTEM', 'SOFT_BODY', 'SURFACE']:
        ...
    show_viewport: bool
    """Display modifier in viewport"""
    show_render: bool
    """Use modifier during render"""
    show_in_editmode: bool
    """Display modifier in Edit mode"""
    show_on_cage: bool
    """Adjust edit cage to modifier result"""
    show_expanded: bool
    """Set modifier expanded in the user interface"""
    is_active: Annotated[bool, "is_animatable=False"]
    """The active modifier in the list"""
    use_pin_to_last: Annotated[bool, "is_animatable=False"]
    """Keep the modifier at the end of the list"""
    @property
    def is_override_data(self) -> bool:
        """In a local override object, whether this modifier comes from the linked reference object, or is local to the override"""
        ...
    use_apply_on_spline: bool
    """Apply this and all preceding deformation modifiers on splines' points rather than on filled curve/surface"""
    @property
    def execution_time(self) -> Annotated[float, "subtype='TIME_ABSOLUTE'", "unit='TIME_ABSOLUTE'", "step=10.0", "precision=3", "is_animatable=False"]:
        """Time in seconds that the modifier took to evaluate. This is only set on evaluated objects. If multiple modifiers run in parallel, execution time is not a reliable metric."""
        ...
    @property
    def persistent_uid(self) -> Annotated[int, "step=1"]:
        """Uniquely identifies the modifier within the modifier stack that it is part of"""
        ...
    use_custom_camera: bool
    """Use custom camera instead of the active camera"""
    use_fuzzy_intersections: bool
    """Treat intersection and contour lines as if they were the same type so they can be chained together"""
    use_fuzzy_all: bool
    """Treat all lines as the same line type so they can be chained together"""
    use_object_instances: bool
    """Allow particle objects and face/vertex instances to show in Line Art"""
    use_edge_overlap: bool
    """Allow edges in the same location (i.e. from edge split) to show properly. May run slower."""
    use_clip_plane_boundaries: bool
    """Allow lines generated by the near/far clipping plane to be shown"""
    crease_threshold: Annotated[float, "subtype='ANGLE'", "unit='ROTATION'", "step=0.009999999776482582", "precision=1"]
    """Angles smaller than this will be treated as creases. Crease angle priority: object Line Art crease override > mesh auto smooth angle > Line Art default crease."""
    split_angle: Annotated[float, "subtype='ANGLE'", "unit='ROTATION'", "step=0.009999999776482582", "precision=1"]
    """Angle in screen space below which a stroke is split in two"""
    smooth_tolerance: Annotated[float, "step=0.05000000074505806", "precision=4"]
    """Strength of smoothing applied on jagged chains"""
    use_loose_as_contour: bool
    """Loose edges will have contour type"""
    invert_source_vertex_group: bool
    """Invert source vertex group values"""
    use_output_vertex_group_match_by_name: bool
    """Match output vertex group based on name"""
    use_face_mark: bool
    """Filter feature lines using Freestyle face marks"""
    use_face_mark_invert: bool
    """Invert face mark filtering"""
    use_face_mark_boundaries: bool
    """Filter feature lines based on face mark boundaries"""
    use_face_mark_keep_contour: bool
    """Preserve contour lines while filtering"""
    chaining_image_threshold: Annotated[float, "subtype='DISTANCE'", "unit='LENGTH'", "step=0.0010000000474974513", "precision=4"]
    """Segments with an image distance smaller than this will be chained together"""
    use_loose_edge_chain: bool
    """Allow loose edges to be chained together"""
    use_geometry_space_chain: bool
    """Use geometry distance for chaining instead of image space"""
    use_detail_preserve: bool
    """Keep the zig-zag "noise" in initial chaining"""
    use_overlap_edge_type_support: bool
    """Allow an edge to have multiple overlapping types. This will create a separate stroke for each overlapping type."""
    stroke_depth_offset: Annotated[float, "subtype='DISTANCE'", "unit='LENGTH'", "step=0.0010000000474974513", "precision=4"]
    """Move strokes slightly towards the camera to avoid clipping while preserve depth for the viewport"""
    use_offset_towards_custom_camera: bool
    """Offset strokes towards selected camera instead of the active camera"""
    source_camera: Annotated[Optional['Object'], "is_animatable=False"]
    """Use specified camera object for generating Line Art strokes"""
    light_contour_object: Annotated[Optional['Object'], "is_animatable=False"]
    """Use this light object to generate light contour"""
    source_type: Literal['COLLECTION', 'OBJECT', 'SCENE']
    """Line Art stroke source type"""
    source_object: Annotated[Optional['Object'], "is_animatable=False"]
    """Generate strokes from this object"""
    source_collection: Annotated[Optional['Collection'], "is_animatable=False"]
    """Generate strokes from the objects in this collection"""
    use_contour: bool
    """Generate strokes from contours lines"""
    use_loose: bool
    """Generate strokes from loose edges"""
    use_crease: bool
    """Generate strokes from creased edges"""
    use_material: bool
    """Generate strokes from borders between materials"""
    use_edge_mark: bool
    """Generate strokes from Freestyle marked edges"""
    use_intersection: bool
    """Generate strokes from intersections"""
    use_light_contour: bool
    """Generate light/shadow separation lines from a reference light object"""
    use_shadow: bool
    """Project contour lines using a light source object"""
    shadow_region_filtering: Literal['NONE', 'ILLUMINATED', 'SHADED', 'ILLUMINATED_ENCLOSED']
    """Select feature lines that comes from lit or shaded regions. Will not affect cast shadow and light contour since they are at the border."""
    silhouette_filtering: Literal['NONE', 'GROUP', 'INDIVIDUAL']
    """Select contour or silhouette"""
    use_multiple_levels: bool
    """Generate strokes from a range of occlusion levels"""
    level_start: Annotated[int, "step=1"]
    """Minimum number of occlusions for the generated strokes"""
    level_end: Annotated[int, "step=1"]
    """Maximum number of occlusions for the generated strokes"""
    target_layer: Annotated[str, "is_animatable=False"]
    """Grease Pencil layer to which assign the generated strokes"""
    target_material: Annotated[Optional['Material'], "is_animatable=False"]
    """Grease Pencil material assigned to the generated strokes"""
    source_vertex_group: Annotated[str, "is_animatable=False"]
    """Match the beginning of vertex group names from mesh objects, match all when left empty"""
    vertex_group: Annotated[str, "is_animatable=False"]
    """Vertex group name for selected strokes"""
    is_baked: bool
    """This modifier has baked data"""
    use_cache: bool
    """Use cached scene data from the first Line Art modifier in the stack. Certain settings will be unavailable."""
    overscan: Annotated[float, "step=0.009999999776482582", "precision=3"]
    """A margin to prevent strokes from ending abruptly at the edge of the image"""
    radius: Annotated[float, "subtype='FACTOR'", "step=0.009999999776482582", "precision=2"]
    """The radius for the generated strokes"""
    opacity: Annotated[float, "subtype='FACTOR'", "step=0.009999999776482582", "precision=2"]
    """The strength value for the generate strokes"""
    use_material_mask: bool
    """Use material masks to filter out occluded strokes"""
    use_material_mask_match: bool
    """Require matching all material masks instead of just one"""
    use_material_mask_bits: list[bool]
    """Mask bits to match from Material Line Art settings"""
    use_intersection_match: bool
    """Require matching all intersection masks instead of just one"""
    use_intersection_mask: list[bool]
    """Mask bits to match from Collection Line Art settings"""
    use_crease_on_smooth: bool
    """Allow crease edges to show inside smooth surfaces"""
    use_crease_on_sharp: bool
    """Allow crease to show on sharp edges"""
    use_image_boundary_trimming: bool
    """Trim all edges right at the boundary of image (including overscan region)"""
    use_back_face_culling: bool
    """Remove all back faces to speed up calculation, this will create edges in different occlusion levels than when disabled"""
    shadow_camera_near: Annotated[float, "step=0.10000000149011612", "precision=2"]
    """Near clipping distance of shadow camera"""
    shadow_camera_far: Annotated[float, "step=0.10000000149011612", "precision=2"]
    """Far clipping distance of shadow camera"""
    shadow_camera_size: Annotated[float, "step=0.10000000149011612", "precision=2"]
    """Represents the "Orthographic Scale" of an orthographic camera. If the camera is positioned at the light's location with this scale, it will represent the coverage of the shadow "camera"."""
    use_invert_collection: bool
    """Select everything except lines from specified collection"""
    use_invert_silhouette: bool
    """Select anti-silhouette lines"""