# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.HydraRenderEngine.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .RenderEngine import RenderEngine
from .Object import Object
from .RenderSettings import RenderSettings

class HydraRenderEngine(RenderEngine):

    is_animation: bool

    is_preview: bool

    @property
    def camera_override(self) -> Annotated[Optional['Object'], "is_animatable=False"]:

        ...
    layer_override: Annotated[list[bool], "subtype='LAYER_MEMBER'"]

    @property
    def resolution_x(self) -> Annotated[int, "subtype='PIXEL'", "step=1"]:

        ...
    @property
    def resolution_y(self) -> Annotated[int, "subtype='PIXEL'", "step=1"]:

        ...
    @property
    def temporary_directory(self) -> Annotated[str, "is_animatable=False"]:

        ...
    @property
    def render(self) -> Annotated[Optional['RenderSettings'], "is_animatable=False"]:

        ...
    use_highlight_tiles: bool

    bl_idname: Annotated[str, "is_animatable=False"]

    bl_label: Annotated[str, "is_animatable=False"]

    bl_use_preview: bool
    """Render engine supports being used for rendering previews of materials, lights and worlds"""
    bl_use_postprocess: bool
    """Apply compositing on render results"""
    bl_use_eevee_viewport: bool
    """Uses EEVEE for viewport shading in Material Preview shading mode"""
    bl_use_custom_freestyle: bool
    """Handles freestyle rendering on its own, instead of delegating it to EEVEE"""
    bl_use_image_save: bool
    """Save images/movie to disk while rendering an animation. Disabling image saving is only supported when bl_use_postprocess is also disabled."""
    bl_use_gpu_context: bool
    """Enable OpenGL context for the render method, for engines that render using OpenGL"""
    bl_use_shading_nodes_custom: bool
    """Don't expose Cycles and EEVEE shading nodes in the node editor user interface, so separate nodes can be used instead"""
    bl_use_spherical_stereo: bool
    """Support spherical stereo camera models"""
    bl_use_stereo_viewport: bool
    """Support rendering stereo 3D viewport"""
    bl_use_materialx: bool
    """Use MaterialX for exporting materials to Hydra"""
    def update(self, *args, **kwargs) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def render_frame_finish(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def bake(self, *args, **kwargs) -> Any: ...
    def view_update(self, *args, **kwargs) -> Any: ...
    def view_draw(self, *args, **kwargs) -> Any: ...
    def update_script_node(self, *args, **kwargs) -> Any: ...
    def update_render_passes(self, *args, **kwargs) -> Any: ...
    def update_custom_camera(self, *args, **kwargs) -> Any: ...
    def tag_redraw(self, *args, **kwargs) -> Any: ...
    def tag_update(self, *args, **kwargs) -> Any: ...
    def begin_result(self, *args, **kwargs) -> Any: ...
    def update_result(self, *args, **kwargs) -> Any: ...
    def end_result(self, *args, **kwargs) -> Any: ...
    def add_pass(self, *args, **kwargs) -> Any: ...
    def get_result(self, *args, **kwargs) -> Any: ...
    def test_break(self, *args, **kwargs) -> Any: ...
    def pass_by_index_get(self, *args, **kwargs) -> Any: ...
    def active_view_get(self, *args, **kwargs) -> Any: ...
    def active_view_set(self, *args, **kwargs) -> Any: ...
    def camera_shift_x(self, *args, **kwargs) -> Any: ...
    def camera_model_matrix(self, *args, **kwargs) -> Any: ...
    def use_spherical_stereo(self, *args, **kwargs) -> Any: ...
    def update_stats(self, *args, **kwargs) -> Any: ...
    def frame_set(self, *args, **kwargs) -> Any: ...
    def update_progress(self, *args, **kwargs) -> Any: ...
    def update_memory_stats(self, *args, **kwargs) -> Any: ...
    def report(self, *args, **kwargs) -> Any: ...
    def error_set(self, *args, **kwargs) -> Any: ...
    def bind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def unbind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def support_display_space_shader(self, *args, **kwargs) -> Any: ...
    def get_preview_pixel_size(self, *args, **kwargs) -> Any: ...
    def free_blender_memory(self, *args, **kwargs) -> Any: ...
    def tile_highlight_set(self, *args, **kwargs) -> Any: ...
    def tile_highlight_clear_all(self, *args, **kwargs) -> Any: ...
    def register_pass(self, *args, **kwargs) -> Any: ...