# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.ImagePreview.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct

class ImagePreview(bpy_struct):

    is_image_custom: bool
    """True if this preview image has been modified by py script, and is no more auto-generated by Blender"""
    image_size: Annotated[list[int], "subtype='PIXEL'", "step=1"]
    """Width and height in pixels"""
    image_pixels: Annotated[list[int], "step=1"]
    """Image pixels, as bytes (always 32-bit RGBA)"""
    image_pixels_float: Annotated[list[float], "step=10.0", "precision=3"]
    """Image pixels components, as floats (RGBA concatenated values)"""
    is_icon_custom: bool
    """True if this preview icon has been modified by py script, and is no more auto-generated by Blender"""
    icon_size: Annotated[list[int], "subtype='PIXEL'", "step=1"]
    """Width and height in pixels"""
    icon_pixels: Annotated[list[int], "step=1"]
    """Icon pixels, as bytes (always 32-bit RGBA)"""
    icon_pixels_float: Annotated[list[float], "step=10.0", "precision=3"]
    """Icon pixels components, as floats (RGBA concatenated values)"""
    @property
    def icon_id(self) -> Annotated[int, "step=1"]:
        """Unique integer identifying this preview as an icon (zero means invalid)"""
        ...
    def reload(self, *args, **kwargs) -> Any: ...