# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.ImagePreview.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct

class ImagePreview(bpy_struct):

    @property
    def is_image_custom(self) -> bool:
        """True if this preview image has been modified by py script, and is no more auto-generated by Blender"""
        ...
    @is_image_custom.setter
    def is_image_custom(self, value: bool):
        ...
    @property
    def image_size(self) -> Annotated[list[int], "subtype='PIXEL'", "step=1"]:
        """Width and height in pixels"""
        ...
    @image_size.setter
    def image_size(self, value: Annotated[list[int], "subtype='PIXEL'", "step=1"]):
        ...
    @property
    def image_pixels(self) -> Annotated[list[int], "step=1"]:
        """Image pixels, as bytes (always 32-bit RGBA)"""
        ...
    @image_pixels.setter
    def image_pixels(self, value: Annotated[list[int], "step=1"]):
        ...
    @property
    def image_pixels_float(self) -> Annotated[list[float], "step=10.0", "precision=3"]:
        """Image pixels components, as floats (RGBA concatenated values)"""
        ...
    @image_pixels_float.setter
    def image_pixels_float(self, value: Annotated[list[float], "step=10.0", "precision=3"]):
        ...
    @property
    def is_icon_custom(self) -> bool:
        """True if this preview icon has been modified by py script, and is no more auto-generated by Blender"""
        ...
    @is_icon_custom.setter
    def is_icon_custom(self, value: bool):
        ...
    @property
    def icon_size(self) -> Annotated[list[int], "subtype='PIXEL'", "step=1"]:
        """Width and height in pixels"""
        ...
    @icon_size.setter
    def icon_size(self, value: Annotated[list[int], "subtype='PIXEL'", "step=1"]):
        ...
    @property
    def icon_pixels(self) -> Annotated[list[int], "step=1"]:
        """Icon pixels, as bytes (always 32-bit RGBA)"""
        ...
    @icon_pixels.setter
    def icon_pixels(self, value: Annotated[list[int], "step=1"]):
        ...
    @property
    def icon_pixels_float(self) -> Annotated[list[float], "step=10.0", "precision=3"]:
        """Icon pixels components, as floats (RGBA concatenated values)"""
        ...
    @icon_pixels_float.setter
    def icon_pixels_float(self, value: Annotated[list[float], "step=10.0", "precision=3"]):
        ...
    @property
    def icon_id(self) -> Annotated[int, "step=1"]:
        """Unique integer identifying this preview as an icon (zero means invalid)"""
        ...
    def reload(self, *args, **kwargs) -> Any: ...