# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.NodeTreeInterfaceSocketString.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .NodeTreeInterfaceSocket import NodeTreeInterfaceSocket
from .NodeTreeInterfacePanel import NodeTreeInterfacePanel

class NodeTreeInterfaceSocketString(NodeTreeInterfaceSocket):

    @property
    def item_type(self) -> Literal['SOCKET', 'PANEL']:
        """Type of interface item"""
        ...
    @property
    def parent(self) -> Annotated[Optional['NodeTreeInterfacePanel'], "is_animatable=False"]:
        """Panel that contains the item"""
        ...
    @property
    def position(self) -> Annotated[int, "step=1"]:
        """Position of the item in its parent panel"""
        ...
    @property
    def index(self) -> Annotated[int, "step=1"]:
        """Global index of the item among all items in the interface"""
        ...
    @property
    def name(self) -> Annotated[str, "is_animatable=False"]:
        """Socket name"""
        ...
    @name.setter
    def name(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def identifier(self) -> Annotated[str, "is_animatable=False"]:
        """Unique identifier for mapping sockets"""
        ...
    @property
    def description(self) -> Annotated[str, "is_animatable=False"]:
        """Socket description"""
        ...
    @description.setter
    def description(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def socket_type(self) -> Annotated[Literal['DEFAULT'], "is_animatable=False"]:
        """Type of the socket generated by this interface item"""
        ...
    @socket_type.setter
    def socket_type(self, value: Annotated[Literal['DEFAULT'], "is_animatable=False"]):
        ...
    @property
    def in_out(self) -> Literal['INPUT', 'OUTPUT']:
        """Input or output socket type"""
        ...
    @property
    def hide_value(self) -> Annotated[bool, "is_animatable=False"]:
        """Hide the socket input value even when the socket is not connected"""
        ...
    @hide_value.setter
    def hide_value(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def hide_in_modifier(self) -> Annotated[bool, "is_animatable=False"]:
        """Don't show the input value in the geometry nodes modifier interface"""
        ...
    @hide_in_modifier.setter
    def hide_in_modifier(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def force_non_field(self) -> Annotated[bool, "is_animatable=False"]:
        """Only allow single value inputs rather than field.
Deprecated. Will be remove in 5.0."""
        ...
    @force_non_field.setter
    def force_non_field(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def is_inspect_output(self) -> Annotated[bool, "is_animatable=False"]:
        """Take link out of node group to connect to root tree output node"""
        ...
    @is_inspect_output.setter
    def is_inspect_output(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def is_panel_toggle(self) -> Annotated[bool, "is_animatable=False"]:
        """This socket is meant to be used as the toggle in its panel header"""
        ...
    @is_panel_toggle.setter
    def is_panel_toggle(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def layer_selection_field(self) -> Annotated[bool, "is_animatable=False"]:
        """Take Grease Pencil Layer or Layer Group as selection field"""
        ...
    @layer_selection_field.setter
    def layer_selection_field(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def menu_expanded(self) -> Annotated[bool, "is_animatable=False"]:
        """Draw the menu socket as an expanded drop-down menu"""
        ...
    @menu_expanded.setter
    def menu_expanded(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def optional_label(self) -> Annotated[bool, "is_animatable=False"]:
        """Indicate that the label of this socket is not necessary to understand its meaning. This may result in the label being skipped in some cases"""
        ...
    @optional_label.setter
    def optional_label(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def attribute_domain(self) -> Literal['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE', 'LAYER']:
        """Attribute domain used by the geometry nodes modifier to create an attribute output"""
        ...
    @attribute_domain.setter
    def attribute_domain(self, value: Literal['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE', 'LAYER']):
        ...
    @property
    def default_attribute_name(self) -> Annotated[str, "is_animatable=False"]:
        """The attribute name used by default when the node group is used by a geometry nodes modifier"""
        ...
    @default_attribute_name.setter
    def default_attribute_name(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def structure_type(self) -> Literal['AUTO', 'DYNAMIC', 'FIELD', 'GRID', 'LIST', 'SINGLE']:
        """What kind of higher order types are expected to flow through this socket"""
        ...
    @structure_type.setter
    def structure_type(self, value: Literal['AUTO', 'DYNAMIC', 'FIELD', 'GRID', 'LIST', 'SINGLE']):
        ...
    @property
    def default_input(self) -> Literal['VALUE', 'INDEX', 'ID_OR_INDEX', 'NORMAL', 'POSITION', 'INSTANCE_TRANSFORM', 'HANDLE_LEFT', 'HANDLE_RIGHT']:
        """Input to use when the socket is unconnected. Requires "Hide Value"."""
        ...
    @default_input.setter
    def default_input(self, value: Literal['VALUE', 'INDEX', 'ID_OR_INDEX', 'NORMAL', 'POSITION', 'INSTANCE_TRANSFORM', 'HANDLE_LEFT', 'HANDLE_RIGHT']):
        ...
    @property
    def bl_socket_idname(self) -> Annotated[str, "is_animatable=False"]:
        """Name of the socket type"""
        ...
    @bl_socket_idname.setter
    def bl_socket_idname(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def subtype(self) -> Annotated[Literal['DEFAULT'], "is_animatable=False"]:
        """Subtype of the default value"""
        ...
    @subtype.setter
    def subtype(self, value: Annotated[Literal['DEFAULT'], "is_animatable=False"]):
        ...
    @property
    def default_value(self) -> Annotated[str, "is_animatable=False"]:
        """Input value used for unconnected socket"""
        ...
    @default_value.setter
    def default_value(self, value: Annotated[str, "is_animatable=False"]):
        ...
    def bl_system_properties_get(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def init_socket(self, *args, **kwargs) -> Any: ...
    def from_socket(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def init_socket(self, *args, **kwargs) -> Any: ...
    def from_socket(self, *args, **kwargs) -> Any: ...