# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated
from .bpy_prop_collection import bpy_prop_collection

from .NodeTreeInterfaceSocket import NodeTreeInterfaceSocket
from .NodeTreeInterfacePanel import NodeTreeInterfacePanel
class NodeTreeInterfaceSocketShader(NodeTreeInterfaceSocket):
    @property
    def item_type(self) -> Literal['SOCKET', 'PANEL']:
        """Type of interface item"""
        ...
    @property
    def parent(self) -> Annotated[Optional['NodeTreeInterfacePanel'], "is_animatable=False"]:
        """Panel that contains the item"""
        ...
    @property
    def position(self) -> Annotated[int, "step=1"]:
        """Position of the item in its parent panel"""
        ...
    @property
    def index(self) -> Annotated[int, "step=1"]:
        """Global index of the item among all items in the interface"""
        ...
    name: Annotated[str, "is_animatable=False"]
    """Socket name"""
    @property
    def identifier(self) -> Annotated[str, "is_animatable=False"]:
        """Unique identifier for mapping sockets"""
        ...
    description: Annotated[str, "is_animatable=False"]
    """Socket description"""
    socket_type: Annotated[Literal['DEFAULT'], "is_animatable=False"]
    """Type of the socket generated by this interface item"""
    @property
    def in_out(self) -> Literal['INPUT', 'OUTPUT']:
        """Input or output socket type"""
        ...
    hide_value: Annotated[bool, "is_animatable=False"]
    """Hide the socket input value even when the socket is not connected"""
    hide_in_modifier: Annotated[bool, "is_animatable=False"]
    """Don't show the input value in the geometry nodes modifier interface"""
    force_non_field: Annotated[bool, "is_animatable=False"]
    """Only allow single value inputs rather than field.
Deprecated. Will be remove in 5.0."""
    is_inspect_output: Annotated[bool, "is_animatable=False"]
    """Take link out of node group to connect to root tree output node"""
    is_panel_toggle: Annotated[bool, "is_animatable=False"]
    """This socket is meant to be used as the toggle in its panel header"""
    layer_selection_field: Annotated[bool, "is_animatable=False"]
    """Take Grease Pencil Layer or Layer Group as selection field"""
    menu_expanded: Annotated[bool, "is_animatable=False"]
    """Draw the menu socket as an expanded drop-down menu"""
    optional_label: Annotated[bool, "is_animatable=False"]
    """Indicate that the label of this socket is not necessary to understand its meaning. This may result in the label being skipped in some cases"""
    attribute_domain: Literal['POINT', 'EDGE', 'FACE', 'CORNER', 'CURVE', 'INSTANCE', 'LAYER']
    """Attribute domain used by the geometry nodes modifier to create an attribute output"""
    default_attribute_name: Annotated[str, "is_animatable=False"]
    """The attribute name used by default when the node group is used by a geometry nodes modifier"""
    structure_type: Literal['AUTO', 'DYNAMIC', 'FIELD', 'GRID', 'LIST', 'SINGLE']
    """What kind of higher order types are expected to flow through this socket"""
    default_input: Literal['VALUE', 'INDEX', 'ID_OR_INDEX', 'NORMAL', 'POSITION', 'INSTANCE_TRANSFORM', 'HANDLE_LEFT', 'HANDLE_RIGHT']
    """Input to use when the socket is unconnected. Requires "Hide Value"."""
    bl_socket_idname: Annotated[str, "is_animatable=False"]
    """Name of the socket type"""
    def bl_system_properties_get(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def init_socket(self, *args, **kwargs) -> Any: ...
    def from_socket(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def init_socket(self, *args, **kwargs) -> Any: ...
    def from_socket(self, *args, **kwargs) -> Any: ...