# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.ParticleSystem.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct
from .ChildParticle import ChildParticle
from .ClothModifier import ClothModifier
from .Object import Object
from .Particle import Particle
from .ParticleSettings import ParticleSettings
from .ParticleTarget import ParticleTarget
from .PointCache import PointCache
from .bpy_prop_collection import bpy_prop_collection

class ParticleSystem(bpy_struct):

    name: Annotated[str, "is_animatable=False"]
    """Particle system name"""
    settings: Annotated['ParticleSettings', "is_animatable=False"]
    """Particle system settings"""
    @property
    def particles(self) -> Annotated[bpy_prop_collection['Particle'], "is_animatable=False"]:
        """Particles generated by the particle system"""
        ...
    @property
    def child_particles(self) -> Annotated[bpy_prop_collection['ChildParticle'], "is_animatable=False"]:
        """Child particles generated by the particle system"""
        ...
    seed: Annotated[int, "subtype='UNSIGNED'", "step=1"]
    """Offset in the random number table, to get a different randomized result"""
    child_seed: Annotated[int, "subtype='UNSIGNED'", "step=1"]
    """Offset in the random number table for child particles, to get a different randomized result"""
    @property
    def is_global_hair(self) -> bool:
        """Hair keys are in global coordinate space"""
        ...
    use_hair_dynamics: bool
    """Enable hair dynamics using cloth simulation"""
    @property
    def cloth(self) -> Annotated['ClothModifier', "is_animatable=False"]:
        """Cloth dynamics for hair"""
        ...
    reactor_target_object: Annotated[Optional['Object'], "is_animatable=False"]
    """For reactor systems, the object that has the target particle system (empty if same object)"""
    reactor_target_particle_system: Annotated[int, "subtype='UNSIGNED'", "step=1"]
    """For reactor systems, index of particle system on the target object"""
    use_keyed_timing: Annotated[bool, "is_animatable=False"]
    """Use key times"""
    @property
    def targets(self) -> Annotated[bpy_prop_collection['ParticleTarget'], "is_animatable=False"]:
        """Target particle systems"""
        ...
    @property
    def active_particle_target(self) -> Annotated[Optional['ParticleTarget'], "is_animatable=False"]:

        ...
    active_particle_target_index: Annotated[int, "subtype='UNSIGNED'", "step=1"]

    vertex_group_density: Annotated[str, "is_animatable=False"]
    """Vertex group to control density"""
    invert_vertex_group_density: bool
    """Negate the effect of the density vertex group"""
    vertex_group_velocity: Annotated[str, "is_animatable=False"]
    """Vertex group to control velocity"""
    invert_vertex_group_velocity: bool
    """Negate the effect of the velocity vertex group"""
    vertex_group_length: Annotated[str, "is_animatable=False"]
    """Vertex group to control length"""
    invert_vertex_group_length: bool
    """Negate the effect of the length vertex group"""
    vertex_group_clump: Annotated[str, "is_animatable=False"]
    """Vertex group to control clump"""
    invert_vertex_group_clump: bool
    """Negate the effect of the clump vertex group"""
    vertex_group_kink: Annotated[str, "is_animatable=False"]
    """Vertex group to control kink"""
    invert_vertex_group_kink: bool
    """Negate the effect of the kink vertex group"""
    vertex_group_roughness_1: Annotated[str, "is_animatable=False"]
    """Vertex group to control roughness 1"""
    invert_vertex_group_roughness_1: bool
    """Negate the effect of the roughness 1 vertex group"""
    vertex_group_roughness_2: Annotated[str, "is_animatable=False"]
    """Vertex group to control roughness 2"""
    invert_vertex_group_roughness_2: bool
    """Negate the effect of the roughness 2 vertex group"""
    vertex_group_roughness_end: Annotated[str, "is_animatable=False"]
    """Vertex group to control roughness end"""
    invert_vertex_group_roughness_end: bool
    """Negate the effect of the roughness end vertex group"""
    vertex_group_size: Annotated[str, "is_animatable=False"]
    """Vertex group to control size"""
    invert_vertex_group_size: bool
    """Negate the effect of the size vertex group"""
    vertex_group_tangent: Annotated[str, "is_animatable=False"]
    """Vertex group to control tangent"""
    invert_vertex_group_tangent: bool
    """Negate the effect of the tangent vertex group"""
    vertex_group_rotation: Annotated[str, "is_animatable=False"]
    """Vertex group to control rotation"""
    invert_vertex_group_rotation: bool
    """Negate the effect of the rotation vertex group"""
    vertex_group_field: Annotated[str, "is_animatable=False"]
    """Vertex group to control field"""
    invert_vertex_group_field: bool
    """Negate the effect of the field vertex group"""
    vertex_group_twist: Annotated[str, "is_animatable=False"]
    """Vertex group to control twist"""
    invert_vertex_group_twist: bool
    """Negate the effect of the twist vertex group"""
    @property
    def point_cache(self) -> Annotated['PointCache', "is_animatable=False"]:

        ...
    @property
    def has_multiple_caches(self) -> bool:
        """Particle system has multiple point caches"""
        ...
    parent: Annotated[Optional['Object'], "is_animatable=False"]
    """Use this object's coordinate system instead of global coordinate system"""
    @property
    def is_editable(self) -> bool:
        """Particle system can be edited in particle mode"""
        ...
    @property
    def is_edited(self) -> bool:
        """Particle system has been edited in particle mode"""
        ...
    @property
    def dt_frac(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """The current simulation time step size, as a fraction of a frame"""
        ...
    def co_hair(self, *args, **kwargs) -> Any: ...
    def uv_on_emitter(self, *args, **kwargs) -> Any: ...
    def mcol_on_emitter(self, *args, **kwargs) -> Any: ...