# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.ParticleSystem.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct
from .ChildParticle import ChildParticle
from .ClothModifier import ClothModifier
from .Object import Object
from .Particle import Particle
from .ParticleSettings import ParticleSettings
from .ParticleTarget import ParticleTarget
from .PointCache import PointCache
from .bpy_prop_collection import bpy_prop_collection

class ParticleSystem(bpy_struct):

    @property
    def name(self) -> Annotated[str, "is_animatable=False"]:
        """Particle system name"""
        ...
    @name.setter
    def name(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def settings(self) -> Annotated['ParticleSettings', "is_animatable=False"]:
        """Particle system settings"""
        ...
    @settings.setter
    def settings(self, value: Annotated['ParticleSettings', "is_animatable=False"]):
        ...
    @property
    def particles(self) -> Annotated[bpy_prop_collection['Particle'], "is_animatable=False"]:
        """Particles generated by the particle system"""
        ...
    @property
    def child_particles(self) -> Annotated[bpy_prop_collection['ChildParticle'], "is_animatable=False"]:
        """Child particles generated by the particle system"""
        ...
    @property
    def seed(self) -> Annotated[int, "subtype='UNSIGNED'", "step=1"]:
        """Offset in the random number table, to get a different randomized result"""
        ...
    @seed.setter
    def seed(self, value: Annotated[int, "subtype='UNSIGNED'", "step=1"]):
        ...
    @property
    def child_seed(self) -> Annotated[int, "subtype='UNSIGNED'", "step=1"]:
        """Offset in the random number table for child particles, to get a different randomized result"""
        ...
    @child_seed.setter
    def child_seed(self, value: Annotated[int, "subtype='UNSIGNED'", "step=1"]):
        ...
    @property
    def is_global_hair(self) -> bool:
        """Hair keys are in global coordinate space"""
        ...
    @property
    def use_hair_dynamics(self) -> bool:
        """Enable hair dynamics using cloth simulation"""
        ...
    @use_hair_dynamics.setter
    def use_hair_dynamics(self, value: bool):
        ...
    @property
    def cloth(self) -> Annotated['ClothModifier', "is_animatable=False"]:
        """Cloth dynamics for hair"""
        ...
    @property
    def reactor_target_object(self) -> Annotated[Optional['Object'], "is_animatable=False"]:
        """For reactor systems, the object that has the target particle system (empty if same object)"""
        ...
    @reactor_target_object.setter
    def reactor_target_object(self, value: Annotated[Optional['Object'], "is_animatable=False"]):
        ...
    @property
    def reactor_target_particle_system(self) -> Annotated[int, "subtype='UNSIGNED'", "step=1"]:
        """For reactor systems, index of particle system on the target object"""
        ...
    @reactor_target_particle_system.setter
    def reactor_target_particle_system(self, value: Annotated[int, "subtype='UNSIGNED'", "step=1"]):
        ...
    @property
    def use_keyed_timing(self) -> Annotated[bool, "is_animatable=False"]:
        """Use key times"""
        ...
    @use_keyed_timing.setter
    def use_keyed_timing(self, value: Annotated[bool, "is_animatable=False"]):
        ...
    @property
    def targets(self) -> Annotated[bpy_prop_collection['ParticleTarget'], "is_animatable=False"]:
        """Target particle systems"""
        ...
    @property
    def active_particle_target(self) -> Annotated[Optional['ParticleTarget'], "is_animatable=False"]:

        ...
    @property
    def active_particle_target_index(self) -> Annotated[int, "subtype='UNSIGNED'", "step=1"]:

        ...
    @active_particle_target_index.setter
    def active_particle_target_index(self, value: Annotated[int, "subtype='UNSIGNED'", "step=1"]):
        ...
    @property
    def vertex_group_density(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control density"""
        ...
    @vertex_group_density.setter
    def vertex_group_density(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_density(self) -> bool:
        """Negate the effect of the density vertex group"""
        ...
    @invert_vertex_group_density.setter
    def invert_vertex_group_density(self, value: bool):
        ...
    @property
    def vertex_group_velocity(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control velocity"""
        ...
    @vertex_group_velocity.setter
    def vertex_group_velocity(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_velocity(self) -> bool:
        """Negate the effect of the velocity vertex group"""
        ...
    @invert_vertex_group_velocity.setter
    def invert_vertex_group_velocity(self, value: bool):
        ...
    @property
    def vertex_group_length(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control length"""
        ...
    @vertex_group_length.setter
    def vertex_group_length(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_length(self) -> bool:
        """Negate the effect of the length vertex group"""
        ...
    @invert_vertex_group_length.setter
    def invert_vertex_group_length(self, value: bool):
        ...
    @property
    def vertex_group_clump(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control clump"""
        ...
    @vertex_group_clump.setter
    def vertex_group_clump(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_clump(self) -> bool:
        """Negate the effect of the clump vertex group"""
        ...
    @invert_vertex_group_clump.setter
    def invert_vertex_group_clump(self, value: bool):
        ...
    @property
    def vertex_group_kink(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control kink"""
        ...
    @vertex_group_kink.setter
    def vertex_group_kink(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_kink(self) -> bool:
        """Negate the effect of the kink vertex group"""
        ...
    @invert_vertex_group_kink.setter
    def invert_vertex_group_kink(self, value: bool):
        ...
    @property
    def vertex_group_roughness_1(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control roughness 1"""
        ...
    @vertex_group_roughness_1.setter
    def vertex_group_roughness_1(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_roughness_1(self) -> bool:
        """Negate the effect of the roughness 1 vertex group"""
        ...
    @invert_vertex_group_roughness_1.setter
    def invert_vertex_group_roughness_1(self, value: bool):
        ...
    @property
    def vertex_group_roughness_2(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control roughness 2"""
        ...
    @vertex_group_roughness_2.setter
    def vertex_group_roughness_2(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_roughness_2(self) -> bool:
        """Negate the effect of the roughness 2 vertex group"""
        ...
    @invert_vertex_group_roughness_2.setter
    def invert_vertex_group_roughness_2(self, value: bool):
        ...
    @property
    def vertex_group_roughness_end(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control roughness end"""
        ...
    @vertex_group_roughness_end.setter
    def vertex_group_roughness_end(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_roughness_end(self) -> bool:
        """Negate the effect of the roughness end vertex group"""
        ...
    @invert_vertex_group_roughness_end.setter
    def invert_vertex_group_roughness_end(self, value: bool):
        ...
    @property
    def vertex_group_size(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control size"""
        ...
    @vertex_group_size.setter
    def vertex_group_size(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_size(self) -> bool:
        """Negate the effect of the size vertex group"""
        ...
    @invert_vertex_group_size.setter
    def invert_vertex_group_size(self, value: bool):
        ...
    @property
    def vertex_group_tangent(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control tangent"""
        ...
    @vertex_group_tangent.setter
    def vertex_group_tangent(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_tangent(self) -> bool:
        """Negate the effect of the tangent vertex group"""
        ...
    @invert_vertex_group_tangent.setter
    def invert_vertex_group_tangent(self, value: bool):
        ...
    @property
    def vertex_group_rotation(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control rotation"""
        ...
    @vertex_group_rotation.setter
    def vertex_group_rotation(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_rotation(self) -> bool:
        """Negate the effect of the rotation vertex group"""
        ...
    @invert_vertex_group_rotation.setter
    def invert_vertex_group_rotation(self, value: bool):
        ...
    @property
    def vertex_group_field(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control field"""
        ...
    @vertex_group_field.setter
    def vertex_group_field(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_field(self) -> bool:
        """Negate the effect of the field vertex group"""
        ...
    @invert_vertex_group_field.setter
    def invert_vertex_group_field(self, value: bool):
        ...
    @property
    def vertex_group_twist(self) -> Annotated[str, "is_animatable=False"]:
        """Vertex group to control twist"""
        ...
    @vertex_group_twist.setter
    def vertex_group_twist(self, value: Annotated[str, "is_animatable=False"]):
        ...
    @property
    def invert_vertex_group_twist(self) -> bool:
        """Negate the effect of the twist vertex group"""
        ...
    @invert_vertex_group_twist.setter
    def invert_vertex_group_twist(self, value: bool):
        ...
    @property
    def point_cache(self) -> Annotated['PointCache', "is_animatable=False"]:

        ...
    @property
    def has_multiple_caches(self) -> bool:
        """Particle system has multiple point caches"""
        ...
    @property
    def parent(self) -> Annotated[Optional['Object'], "is_animatable=False"]:
        """Use this object's coordinate system instead of global coordinate system"""
        ...
    @parent.setter
    def parent(self, value: Annotated[Optional['Object'], "is_animatable=False"]):
        ...
    @property
    def is_editable(self) -> bool:
        """Particle system can be edited in particle mode"""
        ...
    @property
    def is_edited(self) -> bool:
        """Particle system has been edited in particle mode"""
        ...
    @property
    def dt_frac(self) -> Annotated[float, "step=10.0", "precision=3"]:
        """The current simulation time step size, as a fraction of a frame"""
        ...
    def co_hair(self, *args, **kwargs) -> Any: ...
    def uv_on_emitter(self, *args, **kwargs) -> Any: ...
    def mcol_on_emitter(self, *args, **kwargs) -> Any: ...