# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.RenderEngine.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct
from .Object import Object
from .RenderSettings import RenderSettings

class RenderEngine(bpy_struct):

    @property
    def is_animation(self) -> bool:

        ...
    @is_animation.setter
    def is_animation(self, value: bool) -> None:
        ...
    @property
    def is_preview(self) -> bool:

        ...
    @is_preview.setter
    def is_preview(self, value: bool) -> None:
        ...
    @property
    def camera_override(self) -> Annotated[Optional['Object'], "is_animatable=False"]:

        ...
    @property
    def layer_override(self) -> Annotated[list[bool], "subtype='LAYER_MEMBER'"]:

        ...
    @layer_override.setter
    def layer_override(self, value: Annotated[list[bool], "subtype='LAYER_MEMBER'"]) -> None:
        ...
    @property
    def resolution_x(self) -> Annotated[int, "subtype='PIXEL'", "step=1"]:

        ...
    @property
    def resolution_y(self) -> Annotated[int, "subtype='PIXEL'", "step=1"]:

        ...
    @property
    def temporary_directory(self) -> Annotated[str, "is_animatable=False"]:

        ...
    @property
    def render(self) -> Annotated[Optional['RenderSettings'], "is_animatable=False"]:

        ...
    @property
    def use_highlight_tiles(self) -> bool:

        ...
    @use_highlight_tiles.setter
    def use_highlight_tiles(self, value: bool) -> None:
        ...
    @property
    def bl_idname(self) -> Annotated[str, "is_animatable=False"]:

        ...
    @bl_idname.setter
    def bl_idname(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def bl_label(self) -> Annotated[str, "is_animatable=False"]:

        ...
    @bl_label.setter
    def bl_label(self, value: Annotated[str, "is_animatable=False"]) -> None:
        ...
    @property
    def bl_use_preview(self) -> bool:
        """Render engine supports being used for rendering previews of materials, lights and worlds"""
        ...
    @bl_use_preview.setter
    def bl_use_preview(self, value: bool) -> None:
        ...
    @property
    def bl_use_postprocess(self) -> bool:
        """Apply compositing on render results"""
        ...
    @bl_use_postprocess.setter
    def bl_use_postprocess(self, value: bool) -> None:
        ...
    @property
    def bl_use_eevee_viewport(self) -> bool:
        """Uses EEVEE for viewport shading in Material Preview shading mode"""
        ...
    @bl_use_eevee_viewport.setter
    def bl_use_eevee_viewport(self, value: bool) -> None:
        ...
    @property
    def bl_use_custom_freestyle(self) -> bool:
        """Handles freestyle rendering on its own, instead of delegating it to EEVEE"""
        ...
    @bl_use_custom_freestyle.setter
    def bl_use_custom_freestyle(self, value: bool) -> None:
        ...
    @property
    def bl_use_image_save(self) -> bool:
        """Save images/movie to disk while rendering an animation. Disabling image saving is only supported when bl_use_postprocess is also disabled."""
        ...
    @bl_use_image_save.setter
    def bl_use_image_save(self, value: bool) -> None:
        ...
    @property
    def bl_use_gpu_context(self) -> bool:
        """Enable OpenGL context for the render method, for engines that render using OpenGL"""
        ...
    @bl_use_gpu_context.setter
    def bl_use_gpu_context(self, value: bool) -> None:
        ...
    @property
    def bl_use_shading_nodes_custom(self) -> bool:
        """Don't expose Cycles and EEVEE shading nodes in the node editor user interface, so separate nodes can be used instead"""
        ...
    @bl_use_shading_nodes_custom.setter
    def bl_use_shading_nodes_custom(self, value: bool) -> None:
        ...
    @property
    def bl_use_spherical_stereo(self) -> bool:
        """Support spherical stereo camera models"""
        ...
    @bl_use_spherical_stereo.setter
    def bl_use_spherical_stereo(self, value: bool) -> None:
        ...
    @property
    def bl_use_stereo_viewport(self) -> bool:
        """Support rendering stereo 3D viewport"""
        ...
    @bl_use_stereo_viewport.setter
    def bl_use_stereo_viewport(self, value: bool) -> None:
        ...
    @property
    def bl_use_materialx(self) -> bool:
        """Use MaterialX for exporting materials to Hydra"""
        ...
    @bl_use_materialx.setter
    def bl_use_materialx(self, value: bool) -> None:
        ...
    def update(self, *args, **kwargs) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def render_frame_finish(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def bake(self, *args, **kwargs) -> Any: ...
    def view_update(self, *args, **kwargs) -> Any: ...
    def view_draw(self, *args, **kwargs) -> Any: ...
    def update_script_node(self, *args, **kwargs) -> Any: ...
    def update_render_passes(self, *args, **kwargs) -> Any: ...
    def update_custom_camera(self, *args, **kwargs) -> Any: ...
    def tag_redraw(self, *args, **kwargs) -> Any: ...
    def tag_update(self, *args, **kwargs) -> Any: ...
    def begin_result(self, *args, **kwargs) -> Any: ...
    def update_result(self, *args, **kwargs) -> Any: ...
    def end_result(self, *args, **kwargs) -> Any: ...
    def add_pass(self, *args, **kwargs) -> Any: ...
    def get_result(self, *args, **kwargs) -> Any: ...
    def test_break(self, *args, **kwargs) -> Any: ...
    def pass_by_index_get(self, *args, **kwargs) -> Any: ...
    def active_view_get(self, *args, **kwargs) -> Any: ...
    def active_view_set(self, *args, **kwargs) -> Any: ...
    def camera_shift_x(self, *args, **kwargs) -> Any: ...
    def camera_model_matrix(self, *args, **kwargs) -> Any: ...
    def use_spherical_stereo(self, *args, **kwargs) -> Any: ...
    def update_stats(self, *args, **kwargs) -> Any: ...
    def frame_set(self, *args, **kwargs) -> Any: ...
    def update_progress(self, *args, **kwargs) -> Any: ...
    def update_memory_stats(self, *args, **kwargs) -> Any: ...
    def report(self, *args, **kwargs) -> Any: ...
    def error_set(self, *args, **kwargs) -> Any: ...
    def bind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def unbind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def support_display_space_shader(self, *args, **kwargs) -> Any: ...
    def get_preview_pixel_size(self, *args, **kwargs) -> Any: ...
    def free_blender_memory(self, *args, **kwargs) -> Any: ...
    def tile_highlight_set(self, *args, **kwargs) -> Any: ...
    def tile_highlight_clear_all(self, *args, **kwargs) -> Any: ...
    def register_pass(self, *args, **kwargs) -> Any: ...