# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


"""
Online Documentation:
https://docs.blender.org/api/current/bpy.types.UILayout.html
"""

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator, Literal, Annotated

from .bpy_struct import bpy_struct

class UILayout(bpy_struct):

    @property
    def active(self) -> bool:

        ...
    @active.setter
    def active(self, value: bool):
        ...
    @property
    def active_default(self) -> bool:
        """When true, an operator button defined after this will be activated when pressing return(use with popup dialogs)"""
        ...
    @active_default.setter
    def active_default(self, value: bool):
        ...
    @property
    def activate_init(self) -> bool:
        """When true, buttons defined in popups will be activated on first display (use so you can type into a field without having to click on it first)"""
        ...
    @activate_init.setter
    def activate_init(self, value: bool):
        ...
    @property
    def operator_context(self) -> Literal['INVOKE_DEFAULT', 'INVOKE_REGION_WIN', 'INVOKE_REGION_CHANNELS', 'INVOKE_REGION_PREVIEW', 'INVOKE_AREA', 'INVOKE_SCREEN', 'EXEC_DEFAULT', 'EXEC_REGION_WIN', 'EXEC_REGION_CHANNELS', 'EXEC_REGION_PREVIEW', 'EXEC_AREA', 'EXEC_SCREEN']:
        """Typically set to 'INVOKE_REGION_WIN', except some cases in :class:`bpy.types.Menu` when it's set to 'EXEC_REGION_WIN'."""
        ...
    @operator_context.setter
    def operator_context(self, value: Literal['INVOKE_DEFAULT', 'INVOKE_REGION_WIN', 'INVOKE_REGION_CHANNELS', 'INVOKE_REGION_PREVIEW', 'INVOKE_AREA', 'INVOKE_SCREEN', 'EXEC_DEFAULT', 'EXEC_REGION_WIN', 'EXEC_REGION_CHANNELS', 'EXEC_REGION_PREVIEW', 'EXEC_AREA', 'EXEC_SCREEN']):
        ...
    @property
    def enabled(self) -> bool:
        """When false, this (sub)layout is grayed out"""
        ...
    @enabled.setter
    def enabled(self, value: bool):
        ...
    @property
    def alert(self) -> bool:

        ...
    @alert.setter
    def alert(self, value: bool):
        ...
    @property
    def alignment(self) -> Literal['EXPAND', 'LEFT', 'CENTER', 'RIGHT']:

        ...
    @alignment.setter
    def alignment(self, value: Literal['EXPAND', 'LEFT', 'CENTER', 'RIGHT']):
        ...
    @property
    def direction(self) -> Literal['HORIZONTAL', 'VERTICAL']:

        ...
    @property
    def scale_x(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:
        """Scale factor along the X for items in this (sub)layout"""
        ...
    @scale_x.setter
    def scale_x(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]):
        ...
    @property
    def scale_y(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:
        """Scale factor along the Y for items in this (sub)layout"""
        ...
    @scale_y.setter
    def scale_y(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]):
        ...
    @property
    def ui_units_x(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:
        """Fixed size along the X for items in this (sub)layout"""
        ...
    @ui_units_x.setter
    def ui_units_x(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]):
        ...
    @property
    def ui_units_y(self) -> Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]:
        """Fixed size along the Y for items in this (sub)layout"""
        ...
    @ui_units_y.setter
    def ui_units_y(self, value: Annotated[float, "subtype='UNSIGNED'", "step=10.0", "precision=3"]):
        ...
    @property
    def emboss(self) -> Literal['NORMAL', 'NONE', 'PULLDOWN_MENU', 'PIE_MENU', 'NONE_OR_STATUS']:

        ...
    @emboss.setter
    def emboss(self, value: Literal['NORMAL', 'NONE', 'PULLDOWN_MENU', 'PIE_MENU', 'NONE_OR_STATUS']):
        ...
    @property
    def use_property_split(self) -> bool:

        ...
    @use_property_split.setter
    def use_property_split(self, value: bool):
        ...
    @property
    def use_property_decorate(self) -> bool:

        ...
    @use_property_decorate.setter
    def use_property_decorate(self, value: bool):
        ...
    def row(self, *args, **kwargs) -> Any: ...
    def column(self, *args, **kwargs) -> Any: ...
    def panel(self, *args, **kwargs) -> Any: ...
    def panel_prop(self, *args, **kwargs) -> Any: ...
    def column_flow(self, *args, **kwargs) -> Any: ...
    def grid_flow(self, *args, **kwargs) -> Any: ...
    def box(self, *args, **kwargs) -> Any: ...
    def split(self, *args, **kwargs) -> Any: ...
    def menu_pie(self, *args, **kwargs) -> Any: ...
    def icon(self, *args, **kwargs) -> Any: ...
    def enum_item_name(self, *args, **kwargs) -> Any: ...
    def enum_item_description(self, *args, **kwargs) -> Any: ...
    def enum_item_icon(self, *args, **kwargs) -> Any: ...
    def prop(self, *args, **kwargs) -> Any: ...
    def props_enum(self, *args, **kwargs) -> Any: ...
    def prop_menu_enum(self, *args, **kwargs) -> Any: ...
    def prop_with_popover(self, *args, **kwargs) -> Any: ...
    def prop_with_menu(self, *args, **kwargs) -> Any: ...
    def prop_tabs_enum(self, *args, **kwargs) -> Any: ...
    def prop_enum(self, *args, **kwargs) -> Any: ...
    def prop_search(self, *args, **kwargs) -> Any: ...
    def prop_decorator(self, *args, **kwargs) -> Any: ...
    def operator(self, *args, **kwargs) -> Any: ...
    def operator_menu_hold(self, *args, **kwargs) -> Any: ...
    def operator_enum(self, *args, **kwargs) -> Any: ...
    def operator_menu_enum(self, *args, **kwargs) -> Any: ...
    def label(self, *args, **kwargs) -> Any: ...
    def menu(self, *args, **kwargs) -> Any: ...
    def menu_contents(self, *args, **kwargs) -> Any: ...
    def popover(self, *args, **kwargs) -> Any: ...
    def popover_group(self, *args, **kwargs) -> Any: ...
    def separator(self, *args, **kwargs) -> Any: ...
    def separator_spacer(self, *args, **kwargs) -> Any: ...
    def progress(self, *args, **kwargs) -> Any: ...
    def context_pointer_set(self, *args, **kwargs) -> Any: ...
    def context_string_set(self, *args, **kwargs) -> Any: ...
    def template_header(self, *args, **kwargs) -> Any: ...
    def template_ID(self, *args, **kwargs) -> Any: ...
    def template_ID_preview(self, *args, **kwargs) -> Any: ...
    def template_matrix(self, *args, **kwargs) -> Any: ...
    def template_any_ID(self, *args, **kwargs) -> Any: ...
    def template_ID_tabs(self, *args, **kwargs) -> Any: ...
    def template_action(self, *args, **kwargs) -> Any: ...
    def template_search(self, *args, **kwargs) -> Any: ...
    def template_search_preview(self, *args, **kwargs) -> Any: ...
    def template_path_builder(self, *args, **kwargs) -> Any: ...
    def template_modifiers(self, *args, **kwargs) -> Any: ...
    def template_strip_modifiers(self, *args, **kwargs) -> Any: ...
    def template_collection_exporters(self, *args, **kwargs) -> Any: ...
    def template_constraints(self, *args, **kwargs) -> Any: ...
    def template_shaderfx(self, *args, **kwargs) -> Any: ...
    def template_greasepencil_color(self, *args, **kwargs) -> Any: ...
    def template_constraint_header(self, *args, **kwargs) -> Any: ...
    def template_preview(self, *args, **kwargs) -> Any: ...
    def template_curve_mapping(self, *args, **kwargs) -> Any: ...
    def template_curveprofile(self, *args, **kwargs) -> Any: ...
    def template_color_ramp(self, *args, **kwargs) -> Any: ...
    def template_icon(self, *args, **kwargs) -> Any: ...
    def template_icon_view(self, *args, **kwargs) -> Any: ...
    def template_histogram(self, *args, **kwargs) -> Any: ...
    def template_waveform(self, *args, **kwargs) -> Any: ...
    def template_vectorscope(self, *args, **kwargs) -> Any: ...
    def template_layers(self, *args, **kwargs) -> Any: ...
    def template_color_picker(self, *args, **kwargs) -> Any: ...
    def template_palette(self, *args, **kwargs) -> Any: ...
    def template_image_layers(self, *args, **kwargs) -> Any: ...
    def template_image(self, *args, **kwargs) -> Any: ...
    def template_image_settings(self, *args, **kwargs) -> Any: ...
    def template_image_stereo_3d(self, *args, **kwargs) -> Any: ...
    def template_image_views(self, *args, **kwargs) -> Any: ...
    def template_movieclip(self, *args, **kwargs) -> Any: ...
    def template_track(self, *args, **kwargs) -> Any: ...
    def template_marker(self, *args, **kwargs) -> Any: ...
    def template_movieclip_information(self, *args, **kwargs) -> Any: ...
    def template_list(self, *args, **kwargs) -> Any: ...
    def template_running_jobs(self, *args, **kwargs) -> Any: ...
    def template_operator_search(self, *args, **kwargs) -> Any: ...
    def template_menu_search(self, *args, **kwargs) -> Any: ...
    def template_header_3D_mode(self, *args, **kwargs) -> Any: ...
    def template_edit_mode_selection(self, *args, **kwargs) -> Any: ...
    def template_reports_banner(self, *args, **kwargs) -> Any: ...
    def template_input_status(self, *args, **kwargs) -> Any: ...
    def template_status_info(self, *args, **kwargs) -> Any: ...
    def template_node_link(self, *args, **kwargs) -> Any: ...
    def template_node_view(self, *args, **kwargs) -> Any: ...
    def template_node_asset_menu_items(self, *args, **kwargs) -> Any: ...
    def template_modifier_asset_menu_items(self, *args, **kwargs) -> Any: ...
    def template_node_operator_asset_menu_items(self, *args, **kwargs) -> Any: ...
    def template_node_operator_asset_root_items(self, *args, **kwargs) -> Any: ...
    def template_texture_user(self, *args, **kwargs) -> Any: ...
    def template_keymap_item_properties(self, *args, **kwargs) -> Any: ...
    def template_component_menu(self, *args, **kwargs) -> Any: ...
    def template_colorspace_settings(self, *args, **kwargs) -> Any: ...
    def template_colormanaged_view_settings(self, *args, **kwargs) -> Any: ...
    def template_node_socket(self, *args, **kwargs) -> Any: ...
    def template_cache_file(self, *args, **kwargs) -> Any: ...
    def template_cache_file_velocity(self, *args, **kwargs) -> Any: ...
    def template_cache_file_time_settings(self, *args, **kwargs) -> Any: ...
    def template_cache_file_layers(self, *args, **kwargs) -> Any: ...
    def template_recent_files(self, *args, **kwargs) -> Any: ...
    def template_file_select_path(self, *args, **kwargs) -> Any: ...
    def template_event_from_keymap_item(self, *args, **kwargs) -> Any: ...
    def template_light_linking_collection(self, *args, **kwargs) -> Any: ...
    def template_bone_collection_tree(self, *args, **kwargs) -> Any: ...
    def template_grease_pencil_layer_tree(self, *args, **kwargs) -> Any: ...
    def template_node_tree_interface(self, *args, **kwargs) -> Any: ...
    def template_node_inputs(self, *args, **kwargs) -> Any: ...
    def template_asset_shelf_popover(self, *args, **kwargs) -> Any: ...
    def template_popup_confirm(self, *args, **kwargs) -> Any: ...
    def template_shape_key_tree(self, *args, **kwargs) -> Any: ...